name: Nextcloud for Home Assistant
url: https://github.com/haberda/hassio_addons/tree/master/nextcloud
version: dev
slug: nextcloud
arch:
  - aarch64
  - amd64
  - armv7
description: Nextcloud for Home Assistant
startup: system
boot: manual
map:
  - share:rw
  - media:rw
  - ssl:rw
ports:
  443/tcp: 8099
  80/tcp: null
ports_description:
  443/tcp: https port
  80/tcp: http port
webui: https://[HOST]:[PORT:443]
panel_icon: mdi:cloud
backup_exclude: ["*/nextcloud/log/"]
privileged: [SYS_ADMIN]
init: false
image: ghcr.io/haberda/nextcloud/{arch}
